---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "daily"
    pen-pull-requests-limit: 3
    rebase-strategy: "auto"
    commit-message:
      prefix: 'fix'
      include: 'scope'
    groups:
      js:
        applies-to: security-updates
